# Render configuration file for backend deployment
services:
  # Backend API service
  - type: web
    name: skillsync-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false  # Set this in Render dashboard
      - key: JWT_SECRET
        sync: false  # Set this in Render dashboard
      - key: CLOUDINARY_CLOUD_NAME
        sync: false  # Set this in Render dashboard
      - key: CLOUDINARY_API_KEY
        sync: false  # Set this in Render dashboard
      - key: CLOUDINARY_API_SECRET
        sync: false  # Set this in Render dashboard
      - key: EMAIL_USER
        sync: false  # Set this in Render dashboard
      - key: EMAIL_PASS
        sync: false  # Set this in Render dashboard
      - key: FRONTEND_URL
        value: https://your-netlify-app.netlify.app  # Update with your Netlify URL
